language: go

go:
  - 1.3

before_install:
  - go get github.com/jteeuwen/go-bindata/...
  - go get github.com/stretchr/testify/assert
  - go get github.com/cihub/seelog
  - go get github.com/mattn/go-sqlite3 